# Generated by Django 3.2 on 2023-05-11 14:44

from django.db import migrations


INITIAL_TAGS =[
    {'color': 'orange', 'name': 'завтрак', 'slug': 'breakfast'},
    {'color': 'green', 'name': 'обед', 'slug': 'lunch'},
    {'color': 'purple', 'name': 'ужин', 'slug': 'dinner'}
]


def add_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        new_tag = Tag(**tag)
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        Tag.objects.get(slug=tag['slug']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        )
    ]

